### ISSUE TITLE
get_comment_replies returns empty dict/map instead of table when comment has no child replies

### ISSUE THREAD

**Issue by osilkin98** [ocornoc/lbry-comments#24]
## Possible Cases of `get_comment_replies` Method:

There is a case where if a comment exists but has no children, an empty `dict`/`map` is returned rather than a `list`. To demonstrate this, we'll be considering the following index tree:
```
  7
   \
    8
``` 

### 1. The Comment Exists And Has Replies:
Here, the function works as intended, returning a list of replies, in this case just a single 8.
```python
>>> replies = get_comment_replies(id=7)
[8]
>>> type(replies)
<class 'list'>
```
### 2. The Comment Exists But Has No Replies:
This is the weird case. Instead of returning an empty list, an empty dict is returned instead.
```python
>>> replies = get_comment_replies(id=8)
{}
>>> type(replies)
<class 'dict'>
```
### 3. The Comment Doesn't Exist
In this case the function works as intended, and causes the server to return `null`
```python
>>> replies = get_comment_replies(id=9)
None
>>> type(replies)
<class 'NoneType'>
```

### Cause of the problem:

This has to do with how values from the SQLite table are being inserted into the local results table in [`db.lua:917`](https://github.com/ocornoc/lbry-comments/blob/39e0e36ddd6761b8c55607a17c29f47f23dc248c/src/db.lua#L917)
Since SQLite doesn't find any results, it returns `nil` and since Lua views `nil` as being the end of the array, you effectively trick it into returning a `table` object that has a length of 0, and so it somehow messes up and converts it into a dict instead of a normal table

**Comment by ocornoc** [comment]
This is a problem with Lua-CJSON, the JSON library included in OpenResty. The OpenResty fork of Lua-CJSON has [`json.encode_empty_table_as_object`](https://github.com/openresty/lua-cjson/#encode_empty_table_as_object) and [`json.empty_array`](https://github.com/openresty/lua-cjson/#empty_array), which can fix this.
