### ISSUE TITLE
get_claim_data raises wrong error code

### ISSUE THREAD

**Issue by osilkin98** [ocornoc/lbry-comments#5]
`get_claim_data` should raise a JSON-RPC error with the code `-1` if the URI provided is invalid, but it throws `-32603` instead.

Here's a valid permanent URI:

```python
>>> doge = api.get_claim_data("lbry://doge#b0d293791d1761707c23e93eb915a3c1300d17b5")
print(json.dumps(doge, indent=4))
{
    "result": {
        "claim_index": 2,
        "upvotes": 0,
        "downvotes": 0,
        "add_time": 1544916940,
        "lbry_perm_uri": "lbry://doge#b0d293791d1761707c23e93eb915a3c1300d17b5"
    }
}
```

Here is the same URI with the last digit decremented:
```python
>>> fail = api.get_claim_data("lbry://doge#b0d293791d1761707c23e93eb915a3c1300d17b4")
Error from message server 'http://18.233.233.111:2903/api', code -32603
Traceback (most recent call last):
  File "<input>", line 154, in get_claim_data
  File "<input>", line 132, in make_request
lbrynet.extras.daemon.comments.exceptions.InternalMetadataServerError: 
{
  'error': {
    'message': 'uri doesnt exist', 
    'code': -32603
  }
}
```

**Comment by ocornoc** [comment]
Error code `-1` is intended only for malformed URIs (IE, not a full-length permanent claim URI), rather than URIs that don't exist. In actuality, the problem isn't that's not `-32603` (internal error), the problem is that it's not `-36202` (invalid parameters).

**Comment by ocornoc** [comment]
I can fix this tomorrow, but cannot address this today. It will require an if/else in `api.lua`.
